#!/system/bin/sh

############################
# Custom Kernel Settings

# Define Basic Paths:

SD_PATH="/data/media/0"
REACTOR_DATA="$SD_PATH/BlackReactor"
REACTOR_LOGFILE="$REACTOR_DATA/reactor_init.log"
REACTOR_STARTCONFIG="/data/.black_reactor/startconfig"
REACTOR_STARTCONFIG_EARLY="/data/.black_reactor/startconfig_early"
REACTOR_STARTCONFIG_DONE="/data/.black_reactor/startconfig_done"
REACTOR_LOGFILE_SOUND="$REACTOR_DATA/reactor_sound_init.log"
REACTOR_INIT_LOG="$REACTOR_DATA/initialization.log"


REACTOR_S_DATA="/data/BlackReactor"
REACTOR__S_LOGFILE="$REACTOR_S_DATA/initialization.log"

# block devices
SYSTEM_DEVICE="/dev/block/platform/msm_sdcc.1/by-name/system"
CACHE_DEVICE="/dev/block/platform/msm_sdcc.1/by-name/cache"
DATA_DEVICE="/dev/block/platform/msm_sdcc.1/by-name/userdata"

# useful vars
DIR_TRUE=0

busybox mount -o remount,rw -t auto /system
busybox mount -o remount,rw -t auto /data

if [ -e $REACTOR_S_DATA ]; then
DIR_TRUE=1
fi

if [ '$DIR_TRUE' = '0' ]; then
	busybox mkdir $REACTOR_S_DATA
fi

# maintain log file history
	rm $REACTOR__S_LOGFILE.3
	mv $REACTOR__S_LOGFILE.2 $REACTOR__S_LOGFILE.3
	mv $REACTOR__S_LOGFILE.1 $REACTOR__S_LOGFILE.2
	mv $REACTOR__S_LOGFILE $REACTOR__S_LOGFILE.1

# Initialize the log file (chmod to make it readable also via /sdcard link)
	echo $(date) BlackReactor-Kernel initialization started > $REACTOR__S_LOGFILE
	/sbin/busybox chmod 666 $REACTOR__S_LOGFILE
	/sbin/busybox cat /proc/version >> $REACTOR__S_LOGFILE
	echo "=========================" >> $REACTOR__S_LOGFILE
	/sbin/busybox grep ro.build.version /system/build.prop >> $REACTOR__S_LOGFILE
echo "=========================" >> $REACTOR__S_LOGFILE

echo "\n=========================\n" >> $REACTOR__S_LOGFILE
echo "$(date) Tweaking interactive cpufreq gov" >> $REACTOR__S_LOGFILE
tweak_interactive
echo "\n=========================\n" >> $REACTOR__S_LOGFILE

function tweak_interactive() {
echo "20000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate
echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
echo "760000" > /sys/devices/system/cpu/cpufreq/interactive/midrange_freq
echo "1300000" > /sys/devices/system/cpu/cpufreq/interactive/max_normal_freq
echo "1900000" > /sys/devices/system/cpu/cpufreq/interactive/max_boost
echo "65" > /sys/devices/system/cpu/cpufreq/interactive/midrange_go_maxspeed_load
echo "85" > /sys/devices/system/cpu/cpufreq/interactive/go_maxspeed_load
}
