#!/system/bin/sh

############################
# Custom Kernel Settings

# Define Basic Paths:

REACTOR_S_DATA="/data/BlackReactor"
REACTOR__S_LOGFILE="$REACTOR_S_DATA/initialization.log"

# block devices
SYSTEM_DEVICE="/dev/block/platform/msm_sdcc.1/by-name/system"
CACHE_DEVICE="/dev/block/platform/msm_sdcc.1/by-name/cache"
DATA_DEVICE="/dev/block/platform/msm_sdcc.1/by-name/userdata"

# useful vars
FST_CHG_VALUE=$(sed -n 1p /data/BlackReactor/fastchg_current)

 mount -o remount,rw /system
 mount -o remount,rw /data

if [ ! -d $REACTOR_S_DATA ]; then
	echo "Creating Directory..."
	 mkdir -p $REACTOR_S_DATA
fi

# maintain log file history
	rm $REACTOR__S_LOGFILE.3
	mv $REACTOR__S_LOGFILE.2 $REACTOR__S_LOGFILE.3
	mv $REACTOR__S_LOGFILE.1 $REACTOR__S_LOGFILE.2
	mv $REACTOR__S_LOGFILE $REACTOR__S_LOGFILE.1

# Initialize the log file (chmod to make it readable also via /sdcard link)
	echo $(date) BlackReactor-Kernel initialization started > $REACTOR__S_LOGFILE
	chmod 777 $REACTOR__S_LOGFILE
	 cat /proc/version >> $REACTOR__S_LOGFILE
	echo "=========================" >> $REACTOR__S_LOGFILE
	 grep ro.build.version /system/build.prop >> $REACTOR__S_LOGFILE
echo "=========================" >> $REACTOR__S_LOGFILE

echo "$(date) Tweaking interactive cpufreq gov" >> $REACTOR__S_LOGFILE
#############
echo "20000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate
echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
echo "760000" > /sys/devices/system/cpu/cpufreq/interactive/midrange_freq
echo "1300000" > /sys/devices/system/cpu/cpufreq/interactive/max_normal_freq
echo "1900000" > /sys/devices/system/cpu/cpufreq/interactive/max_boost
echo "65" > /sys/devices/system/cpu/cpufreq/interactive/midrange_go_maxspeed_load
echo "85" > /sys/devices/system/cpu/cpufreq/interactive/go_maxspeed_load
#############
echo "\n=========================\n" >> $REACTOR__S_LOGFILE
if [ ! $FST_CHG_VALUE -eq 0 ]; then
	echo 1 > /sys/kernel/fast_charge/force_fast_charge
fi
echo "Previous value of fastchg_current: $FST_CHG_VALUE" >> $REACTOR__S_LOGFILE
echo "$(date) Running setcurr: $FST_CHG_VALUE" >> $REACTOR__S_LOGFILE
setcurr $FST_CHG_VALUE >> $REACTOR__S_LOGFILE
echo "\n=========================\n" >> $REACTOR__S_LOGFILE
echo "$(date) End Log" >> $REACTOR__S_LOGFILE
echo "\n=========================\n" >> $REACTOR__S_LOGFILE