#!/system/bin/sh
CURR=$1
if [ $CURR -lt 2200 ]; then
	echo 'Setting fast charge current to: '$CURR
	echo  $CURR > /sys/kernel/fast_charge_current/force_fast_charge_current
	echo 'Done'
	mount -o remount,rw /system
	if [ ! -d /system/su.d ]; then
		mkdir /system/su.d
	fi
	echo "#!/system/bin/sh" > /system/su.d/fast_charge_current.sh
	echo "echo $CURR > /sys/kernel/fast_charge_current/force_fast_charge_current" > /system/su.d/fast_charge_current.sh
	chmod 755 /system/su.d/fast_charge_current.sh 
	exit 0
fi
echo 'Entered Current: '$CURR' is greater than max allowed current'
exit 1