#!/system/bin/sh
if [ $# -eq 0 ]; then
	echo "Enter a current value"
	exit 1
fi

CURR=$1
if [ $CURR -lt 2200 ]; then
	echo 'Setting fast charge current to: '$CURR
	echo  $CURR > /sys/kernel/fast_charge_current/force_fast_charge_current
	echo 'Done'
	echo $CURR > /data/BlackReactor/fastchg_current
	exit 0
fi
echo 'Entered Current: '$CURR' is greater than max allowed current'
exit 1
